FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_BASE_ROUTE=http://localhost:3000
ENV VITE_BASE_ROUTE=$VITE_BASE_ROUTE

RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "exec", "vite", "preview", "--host"]
